services:
  comicopds:
    build: .
    ports:
      - "8080:8080"
    environment:
      CONTENT_BASE_DIR: /library
      PAGE_SIZE: "50"
      SERVER_BASE: "http://10.0.0.1"   # <- set to your public domain
      URL_PREFIX: ""                               # or "/comics" if served under a subpath
      DISABLE_AUTH: "false"
      OPDS_BASIC_USER: "admin"
      OPDS_BASIC_PASS: "change-me"
      ACTIVATE_CRON: "true"
      CRON_SCHEDULE: "0 * * * *"
      AUTO_INDEX_ON_START: "false"
      PRECACHE_THUMBS: "true"
      PRECACHE_ON_START: "false"   #  trigger at boot
      THUMB_WORKERS: "3"   # tune for your CPU/IO
    volumes:
      - "./Comics:/library:ro"
      - ./data:/data
