version: '3.3'
services:
  comicopds:
    image: comicopds
    container_name: comicopds
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      #- '/opt/data/Comics/ComicRack:/library:ro'
      #- '/home/drudoo/Pi1/Comics/ComicRack:/library:ro'
      - '${PWD}/CT/:/library:ro'
      - '${PWD}/thumbnails:/thumbnails'
      - '${PWD}/:/app'
